"""Authoring source for the Evidence Playbook, and its generator.

Organizer only, never shipped. The rules are plain text here so they can be
edited and reviewed in a diff. Running this file rewrites the encoded
`workshop/playbook.py` that the participant tree carries.

    uv run python scripts/panel.py          # rewrite workshop/playbook.py
    uv run python scripts/panel.py --show   # print the rules, organizer side

Why the shipped copy is encoded: an agent pointed at the participant repository
greps it, and these rules would hand over the legal judgment the participant is
supposed to supply. Encoding stops a grep. It stops nothing else, and the
generated file says so in its own docstring.
"""

import base64
import json
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "workshop" / "playbook.py"

SECTIONS = [
    [
        "1. Scope the Evidence",
        "Use this client's documents, in the version that was in effect.",
        [
            [
                "Evidence is what was in effect on the question date",
                "An effective period ends on the day its replacement starts, so a clause "
                "replaced on 1 April does not govern on 1 April.",
            ],
            [
                "A replaced clause still governs its own period",
                "A clause that was later replaced is the right answer to a question dated "
                "while it governed.",
            ],
            [
                "Evidence comes from this client's file",
                "A clause that reads perfectly and belongs to another client is a "
                "confidentiality incident, and it is the most expensive failure here.",
            ],
        ],
    ],
    [
        "2. Judge the Source",
        "An agreement proves the rule. A record proves what happened.",
        [
            [
                "The instrument governs, the memo reports",
                "A schedule, an amendment, and an executed exhibit state what the parties "
                "agreed; an internal summary states what somebody believed.",
            ],
            [
                "A memo can be the only record of a fact",
                "The only account of an inspection written at the time may be an internal "
                "memo, so rank a document on what it records.",
            ],
        ],
    ],
    [
        "3. Return the Whole Answer",
        "One rule can need several chunks, and several chunks can be one source.",
        [
            [
                "A clause and its exception are one answer",
                "A clause that is expressly subject to a definition or an exclusion is half "
                "an answer, and the half you have points the wrong way.",
            ],
            [
                "Five copies of one note are one source",
                "Each copy carries its own document identifier, so removing repeats by "
                "document identifier leaves all five in place.",
            ],
        ],
    ],
]


TEMPLATE = '''"""Panel content for the web app. Generated by scripts/panel.py, do not edit.

Encoded on purpose, and this is the reason why. These rules are the legal half
of the exercise. They render in the browser so a person reads them and decides
what to do. They are encoded so that a coding agent pointed at this repository
does not absorb the legal judgment by grepping for it and hand back an answer
the person never reasoned about.

That is all the encoding does. It stops a grep, it is not a security boundary,
and anyone who decodes this has decided to, which is a different act from
stumbling across it. The real separation in this workshop is that the held-out
questions are not in the participant repository at all.

AGENTS.md deliberately does give an agent the mechanical facts, the payload
fields and the existence of extra vectors, so nobody burns thirty minutes
rediscovering the repository. The mechanics are not the lesson. The judgment is.

Each section carries a title, a one-line summary, and its rules. A rule states
the legal problem and what safe evidence looks like. It never names the Qdrant
feature that solves it, because finding that is the exercise.

This module renders the panel and nothing else. It has no command that prints
the rules, because one would undo the encoding above: an agent that reads this
docstring would simply run it. To read them, open the app.
"""

import base64
import json

_PANEL = (
{blob}
)

SECTIONS = [
    (title, summary, [tuple(rule) for rule in rules])
    for title, summary, rules in json.loads(base64.b64decode(_PANEL))
]


def demo():
    """Self-check: the panel decodes into readable sections and rules."""
    assert len(SECTIONS) == {sections}, SECTIONS
    assert sum(len(rules) for _, _, rules in SECTIONS) == {rules}
    for title, summary, items in SECTIONS:
        assert title and summary and items
        for rule_title, body in items:
            assert rule_title[0].isupper() and body.endswith("."), rule_title
    return "playbook.py self-check passed"


if __name__ == "__main__":
    print(demo())
'''


def show():
    """Print the rules from the plain-text source above. Never ships."""
    for title, summary, items in SECTIONS:
        print(f"\n{title}\n{summary}")
        for rule_title, body in items:
            print(f"\n  {rule_title}")
            print("\n".join("    " + line for line in textwrap.wrap(body, 84)))


def main():
    blob = base64.b64encode(json.dumps(SECTIONS).encode()).decode()
    TARGET.write_text(
        TEMPLATE.format(
            blob="\n".join('    "%s"' % line for line in textwrap.wrap(blob, 88)),
            sections=len(SECTIONS),
            rules=sum(len(rules) for _, _, rules in SECTIONS),
        )
    )
    print(f"wrote {TARGET.relative_to(ROOT)}: {len(SECTIONS)} sections, "
          f"{sum(len(r) for _, _, r in SECTIONS)} rules")


if __name__ == "__main__":
    import sys

    show() if "--show" in sys.argv else main()
