"""Build the participant repository.

The held-out questions are kept out by not copying them, which works, unlike
encrypting them in a repository the participants clone.

    uv run python scripts/ship.py ../qdrant-legal-lab-participants

Copies only what a participant needs, and replaces workshop/questions.py with a
generated file holding the twelve disclosed calibration questions inline, so
nothing in the shipped tree imports the held-out set.
"""

import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Everything a participant needs, and nothing else.
SHIP = [
    "README.md",
    "AGENTS.md",
    "CLAUDE.md",
    ".env.example",
    ".gitignore",
    ".python-version",
    "pyproject.toml",
    "uv.lock",
    "workshop/lab.py",
    "workshop/run.py",
    "workshop/score.py",
    "workshop/client.py",
    "workshop/app.py",
    "workshop/playbook.py",
]

# Named so a reader can see the decision rather than infer it from an absence.
WITHHELD = {
    "workshop/heldout.py": "the questions they are scored on",
    "workshop/validation.py": "authoring source for the held-out set",
    "workshop/questions.py": "regenerated with the calibration set only",
    "workshop/corpus.py": "its comments document the three case constructions",
    "workshop/vectors.py": "names every model behind every representation",
    "workshop/bench.py": "organizer measurement, reveals the whole lever ladder",
    "workshop/ingest.py": "organizer only, needs a write key",
    "workshop/clausebank.py": "organizer only, used at ingest",
    "instructions.md": "the build brief",
    "DECISIONS.md": "the build ledger",
    "experiments.jsonl": "every measured configuration",
    ".env": "organizer credentials",
}

TEMPLATE = '''"""The calibration questions, generated by scripts/ship.py. Do not edit.

These twelve teach the relevance rubric. They are not the questions you are
scored on. The probes below are shown and never counted: nothing we have tried
retrieves their evidence, and they are there so nobody believes the job is done.
"""

MATTERS = {matters}

CALIBRATION = {calibration}

PROBES = {probes}
'''


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    target = Path(sys.argv[1]).resolve()
    if target == ROOT:
        sys.exit("refusing to overwrite the organizer repository")
    if target.exists():
        shutil.rmtree(target)

    for name in SHIP:
        source = ROOT / name
        if not source.exists():
            sys.exit(f"missing {name}")
        destination = target / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)

    from workshop.questions import CALIBRATION, MATTERS, PROBES

    # The scorer needs the graded passage ids. It does not need the notes that
    # say which lever fixes the question; shipping those hands over the ladder
    # one question at a time.
    answer_key = {"construction", "rationale", "improvement"}
    strip = lambda qs: [{k: v for k, v in q.items() if k not in answer_key} for q in qs]

    (target / "workshop/questions.py").write_text(
        TEMPLATE.format(
            matters=json.dumps(MATTERS, indent=4),
            calibration=json.dumps(strip(CALIBRATION), indent=4),
            probes=json.dumps(strip(PROBES), indent=4),
        )
    )

    # questions.py is in WITHHELD because the organizer version is withheld;
    # the generated replacement above is the one that ships.
    forbidden = set(WITHHELD) - {"workshop/questions.py"}
    # A participant should not have to type a URL and a key from a slide. If the
    # read-only key exists, ship a filled .env; if it does not, say so loudly,
    # because the fallback in client.py would otherwise hand out the write key.
    import os

    from dotenv import load_dotenv

    load_dotenv(ROOT / ".env")
    readonly = os.getenv("QDRANT_READONLY_API_KEY", "").strip()
    url = os.getenv("QDRANT_URL", "").strip()
    if readonly and url:
        (target / ".env").write_text(
            f"QDRANT_URL={url}\n"
            f"QDRANT_READONLY_API_KEY={readonly}\n"
            f"QDRANT_COLLECTION={os.getenv('QDRANT_COLLECTION', 'legal_lab_v1')}\n"
            "OPENAI_API_KEY=\n"
            f"OPENAI_MODEL={os.getenv('OPENAI_MODEL', 'gpt-5.6-luna')}\n"
        )
        print("shipped a filled .env using the read-only key")
    else:
        print("WARNING: QDRANT_READONLY_API_KEY is not set in .env.")
        print("         Participants will have nothing to connect with, and if they are")
        print("         handed the write key instead, thirty laptops can delete the")
        print("         collection. Create a read-only, collection-scoped key first.")

    leaked = [
        path.relative_to(target).as_posix()
        for path in target.rglob("*")
        if path.is_file() and path.relative_to(target).as_posix() in forbidden
    ]
    if leaked:
        sys.exit(f"held-out material reached the participant tree: {leaked}")

    held = {q["question_id"] for q in __import__(
        "workshop.questions", fromlist=["HELD_OUT"]).HELD_OUT}
    for path in target.rglob("*.py"):
        text = path.read_text()
        found = sorted(q for q in held if q in text)
        if found:
            sys.exit(f"{path.name} mentions held-out question ids: {found}")

    print(f"shipped {len(SHIP) + 1} files to {target}")
    print("withheld:")
    for name, why in WITHHELD.items():
        print(f"  {name:28} {why}")


if __name__ == "__main__":
    sys.path.insert(0, str(ROOT))
    main()
