"""Build the participant repository.

The held-out questions are kept out by not copying them, which works, unlike
encrypting them in a repository the participants clone.

    uv run python scripts/ship.py ../qdrant-legal-lab-participants

Copies only what a participant needs, and replaces workshop/questions.py with a
generated file holding the twelve disclosed calibration questions inline, so
nothing in the shipped tree imports the held-out set.
"""

import json
import getpass
import os
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Everything a participant needs, and nothing else.
SHIP = [
    "README.md",
    "AGENTS.md",
    "CLAUDE.md",
    ".env.example",
    ".gitignore",
    ".python-version",
    "pyproject.toml",
    "uv.lock",
    "lab.py",
    "workshop/run.py",
    "workshop/score.py",
    "workshop/client.py",
    "workshop/setup.py",
    "workshop/app.py",
    "workshop/agent.py",
    "workshop/display.py",
    "workshop/playbook.py",
]

# Named so a reader can see the decision rather than infer it from an absence.
WITHHELD = {
    "workshop/heldout.py": "the questions they are scored on",
    "workshop/validation.py": "authoring source for the held-out set",
    "workshop/questions.py": "regenerated with the calibration set only",
    "workshop/corpus.py": "its comments document the three case constructions",
    "workshop/vectors.py": "names every model behind every representation",
    "workshop/bench.py": "organizer measurement, reveals the whole lever ladder",
    "workshop/ingest.py": "organizer only, needs a write key",
    "workshop/clausebank.py": "organizer only, used at ingest",
    "scripts/panel.py": "plain-text source of the playbook rules",
    "FACILITATOR.md": "the run sheet, with every answer in it",
    "SLIDES.md": "the deck, including the reveal",
    "scripts/reference_lab.py": "the tuned solution",
    "instructions.md": "the build brief",
    "DECISIONS.md": "the build ledger",
    "experiments.jsonl": "every measured configuration",
    ".env": "organizer credentials",
}

TEMPLATE = '''"""The calibration questions, generated by scripts/ship.py. Do not edit.

These twelve teach the relevance rubric. They are not the questions you are
scored on. The probes below are shown and never counted: nothing we have tried
retrieves their evidence, and they are there so nobody believes the job is done.
"""

MATTERS = {matters}

CALIBRATION = {calibration}

PROBES = {probes}
'''


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    target = Path(sys.argv[1]).resolve()
    if target == ROOT:
        sys.exit("refusing to overwrite the organizer repository")
    if target.exists():
        shutil.rmtree(target)

    for name in SHIP:
        source = ROOT / name
        if not source.exists():
            sys.exit(f"missing {name}")
        destination = target / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)

    from workshop.questions import CALIBRATION, MATTERS, PROBES

    # The scorer needs the graded chunk ids. It does not need the notes that
    # say which lever fixes the question; shipping those hands over the ladder
    # one question at a time.
    answer_key = {"construction", "rationale", "improvement"}
    strip = lambda qs: [{k: v for k, v in q.items() if k not in answer_key} for q in qs]

    (target / "workshop/questions.py").write_text(
        TEMPLATE.format(
            matters=json.dumps(MATTERS, indent=4),
            calibration=json.dumps(strip(CALIBRATION), indent=4),
            probes=json.dumps(strip(PROBES), indent=4),
        )
    )

    # questions.py is in WITHHELD because the organizer version is withheld;
    # the generated replacement above is the one that ships.
    # questions.py is withheld in its organizer form, then regenerated above.
    # The organizer .env must never reach the participant package.
    forbidden = set(WITHHELD) - {"workshop/questions.py"}

    from dotenv import load_dotenv

    load_dotenv(ROOT / ".env")
    readonly = os.getenv("QDRANT_READONLY_API_KEY", "").strip()
    url = os.getenv("QDRANT_URL", "").strip()
    openai = os.getenv("OPENAI_API_KEY", "").strip()
    if not readonly or not url or not openai:
        sys.exit(
            "Set QDRANT_URL, QDRANT_READONLY_API_KEY, and OPENAI_API_KEY "
            "in the organizer .env first."
        )

    password = os.getenv("WORKSHOP_SETUP_PASSWORD", "")
    if not password:
        if not sys.stdin.isatty():
            sys.exit("Set WORKSHOP_SETUP_PASSWORD or run ship.py in an interactive terminal.")
        password = getpass.getpass("Password participants will enter: ")
        confirmation = getpass.getpass("Confirm workshop password: ")
        if password != confirmation:
            sys.exit("Passwords did not match.")
    if len(password) < 10:
        sys.exit("Use a workshop password with at least 10 characters.")

    from workshop.setup import encrypt

    plaintext = (
        f"QDRANT_URL={url}\n"
        f"QDRANT_READONLY_API_KEY={readonly}\n"
        f"QDRANT_COLLECTION={os.getenv('QDRANT_COLLECTION', 'legal_lab_v2')}\n"
        f"OPENAI_API_KEY={openai}\n"
        f"OPENAI_MODEL={os.getenv('OPENAI_MODEL', 'gpt-5.6-luna')}\n"
    ).encode()
    (target / ".env.enc").write_bytes(encrypt(plaintext, password))
    print("shipped encrypted workshop credentials as .env.enc")

    leaked = [
        path.relative_to(target).as_posix()
        for path in target.rglob("*")
        if path.is_file() and path.relative_to(target).as_posix() in forbidden
    ]
    if leaked:
        sys.exit(f"held-out material reached the participant tree: {leaked}")

    held = {q["question_id"] for q in __import__(
        "workshop.questions", fromlist=["HELD_OUT"]).HELD_OUT}
    for path in target.rglob("*.py"):
        text = path.read_text()
        found = sorted(q for q in held if q in text)
        if found:
            sys.exit(f"{path.name} mentions held-out question ids: {found}")

    print(f"shipped {len(SHIP) + 2} files to {target}")
    print("withheld:")
    for name, why in WITHHELD.items():
        print(f"  {name:28} {why}")


if __name__ == "__main__":
    sys.path.insert(0, str(ROOT))
    main()
