"""Build the participant repository.

The held-out questions are kept out by not copying them, which works, unlike
encrypting them in a repository the participants clone.

    uv run python scripts/ship.py ../qdrant-legal-lab-participants

Copies only what a participant needs, and replaces workshop/questions.py with a
generated file holding the fourteen disclosed calibration questions inline, so
nothing in the shipped tree imports the held-out set.
"""

import json
import getpass
import os
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Everything a participant needs, and nothing else.
SHIP = [
    "README.md",
    "AGENTS.md",
    "CLAUDE.md",
    ".env.example",
    ".gitignore",
    ".python-version",
    "pyproject.toml",
    "uv.lock",
    "lab.py",
    "workshop/run.py",
    "workshop/score.py",
    "workshop/client.py",
    "workshop/setup.py",
    "workshop/app.py",
    "workshop/agent.py",
    "workshop/display.py",
    "workshop/playbook.py",
]

# Named so a reader can see the decision rather than infer it from an absence.
WITHHELD = {
    "workshop/heldout.py": "the questions they are scored on",
    "workshop/validation.py": "authoring source for the held-out set",
    "workshop/questions.py": "regenerated with the calibration set only",
    "workshop/corpus.py": "its comments document the three case constructions",
    "workshop/vectors.py": "names every model behind every representation",
    "workshop/bench.py": "organizer measurement, reveals the whole lever ladder",
    "workshop/ingest.py": "organizer only, needs a write key",
    "workshop/clausebank.py": "organizer only, used at ingest",
    "scripts/panel.py": "plain-text source of the playbook rules",
    "FACILITATOR.md": "the run sheet, with every answer in it",
    "scripts/reference_lab.py": "the tuned solution",
    "instructions.md": "the build brief",
    "DECISIONS.md": "the build ledger",
    "experiments.jsonl": "every measured configuration",
    ".env": "organizer credentials",
}

TEMPLATE = '''"""The calibration questions, generated by scripts/ship.py. Do not edit.

These fourteen teach the relevance rubric and are the board you are scored on.
Two of them are listed in CHALLENGE_IDS: nothing anyone has tried retrieves
their evidence, and they count like the rest, so the best known total is below
100. A larger set of questions stays with the facilitator.
"""

MATTERS = {matters}

CALIBRATION = {calibration}

CHALLENGE_IDS = {challenge_ids}
'''


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    target = Path(sys.argv[1]).resolve()
    if target == ROOT:
        sys.exit("refusing to overwrite the organizer repository")
    if target.exists():
        shutil.rmtree(target)


    for name in SHIP:
        source = ROOT / name
        if not source.exists():
            sys.exit(f"missing {name}")
        destination = target / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)

    # score.py's self-check is organizer verification. It imports corpus and
    # validation, which do not ship, so it raises ModuleNotFoundError on a
    # participant laptop, and it names chunks that are controlling evidence for
    # a held-out question. Drop it and keep the scorer itself.
    scorer = target / "workshop/score.py"
    text = scorer.read_text()
    marker = "def demo():"
    if marker not in text:
        sys.exit("score.py has no demo() to strip; check ship.py against the scorer")
    scorer.write_text(text[: text.index(marker)].rstrip() + "\n")

    from workshop.questions import CALIBRATION, CHALLENGE_IDS, MATTERS

    # The scorer reads question, matter_id, as_of, controlling, and supporting.
    # Everything else is authoring material. The notes hand over the ladder one
    # question at a time, and the distractor and inapplicable lists name chunks
    # that are controlling evidence for a held-out question.
    answer_key = {"construction", "rationale", "improvement", "inapplicable", "distractor"}
    strip = lambda qs: [{k: v for k, v in q.items() if k not in answer_key} for q in qs]

    (target / "workshop/questions.py").write_text(
        TEMPLATE.format(
            matters=json.dumps(MATTERS, indent=4),
            calibration=json.dumps(strip(CALIBRATION), indent=4),
            challenge_ids=json.dumps(CHALLENGE_IDS, indent=4),
        )
    )

    # questions.py is in WITHHELD because the organizer version is withheld;
    # the generated replacement above is the one that ships.
    # questions.py is withheld in its organizer form, then regenerated above.
    # The organizer .env must never reach the participant package.
    forbidden = set(WITHHELD) - {"workshop/questions.py"}

    from dotenv import load_dotenv

    load_dotenv(ROOT / ".env")
    readonly = os.getenv("QDRANT_READONLY_API_KEY", "").strip()
    url = os.getenv("QDRANT_URL", "").strip()
    openai = os.getenv("OPENAI_API_KEY", "").strip()
    if not readonly or not url or not openai:
        sys.exit(
            "Set QDRANT_URL, QDRANT_READONLY_API_KEY, and OPENAI_API_KEY "
            "in the organizer .env first."
        )

    password = os.getenv("WORKSHOP_SETUP_PASSWORD", "")
    if not password:
        if not sys.stdin.isatty():
            sys.exit("Set WORKSHOP_SETUP_PASSWORD or run ship.py in an interactive terminal.")
        password = getpass.getpass("Password participants will enter: ")
        confirmation = getpass.getpass("Confirm workshop password: ")
        if password != confirmation:
            sys.exit("Passwords did not match.")
    if len(password) < 10:
        sys.exit("Use a workshop password with at least 10 characters.")

    from workshop.setup import encrypt

    plaintext = (
        f"QDRANT_URL={url}\n"
        f"QDRANT_READONLY_API_KEY={readonly}\n"
        f"QDRANT_COLLECTION={os.getenv('QDRANT_COLLECTION', 'legal_lab_v2')}\n"
        f"OPENAI_API_KEY={openai}\n"
        f"OPENAI_MODEL={os.getenv('OPENAI_MODEL', 'gpt-5.6-luna')}\n"
    ).encode()
    (target / ".env.enc").write_bytes(encrypt(plaintext, password))
    print("shipped encrypted workshop credentials as .env.enc")

    leaked = [
        path.relative_to(target).as_posix()
        for path in target.rglob("*")
        if path.is_file() and path.relative_to(target).as_posix() in forbidden
    ]
    if leaked:
        sys.exit(f"held-out material reached the participant tree: {leaked}")

    held = {q["question_id"] for q in __import__(
        "workshop.questions", fromlist=["HELD_OUT"]).HELD_OUT}
    for path in target.rglob("*.py"):
        text = path.read_text()
        found = sorted(q for q in held if q in text)
        if found:
            sys.exit(f"{path.name} mentions held-out question ids: {found}")

    print(f"shipped {len(SHIP) + 2} files to {target}")
    print("withheld:")
    for name, why in WITHHELD.items():
        print(f"  {name:28} {why}")


if __name__ == "__main__":
    sys.path.insert(0, str(ROOT))
    try:
        main()
    except BaseException:
        target = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else None
        if target and target != ROOT and target.exists():
            shutil.rmtree(target)
            print(f"removed the partial tree at {target}", file=sys.stderr)
        raise
